RL_params:
  init:
    action_type: "init"

    move_to_home:
      robot: "kuka"
      skill_type: "joint_move_to"
      target_frame: "home"
      acceleration_scaling: 1
      velocity_scaling: 1
      relative_position: [0.0,0.0,0.4]
      relative_orientation: [0.0,0.0,0.0,1.0]
    open_gripper:
      skill_type: "parallel_gripper_move"
      control_mode: "open"

  main:
    action_type: "movement"

    move_to_coke:
      skill_type: "joint_move_to"
      target_frame: "coke_approach"
      acceleration_scaling: 1
      velocity_scaling: 1
      relative_position: [0.0,0.0,0.0]
      relative_orientation: [0.0,0.0,0.0,1.0]

    move_to_hole:
      target_frame: "hole_2"
      acceleration_scaling: 1
      velocity_scaling: 1
      skill_type: "joint_move_to"
      relative_position: [0.0,0.0,0.0]
      relative_orientation: [0.0,0.0,0.0,1.0]

  coke_pick_and_place:
    # robot: "kr_50_r2500"
    # end_effector: "closed_tip"
    action_type: "pick_and_place"
    object_name: "visual_coke"
    location_name: "in_hole_2"

    open_gripper:
      skill_type: "parallel_gripper_move"
      control_mode: "open"
      torque: 60
      torque_max_variation: 5
    close_gripper:
      skill_type: "parallel_gripper_move"
      control_mode: "close"
      torque: 80
      torque_max_variation: 5
    positioning:
      target_frame : "coke_grasp"
      acceleration_scaling: 0.5
      velocity_scaling: 0.5
      skill_type: "joint_move_to"
      relative_position: [0.0,0.0,0.0]
      relative_orientation: [0.0,0.0,0.0,1.0]

      relative_position_max_variation: [0.02,0.02,0.02]
      acceleration_scaling_max_variation: 0.1
      velocity_scaling_max_variation: 0.1

    approach:
      target_frame : "on_hole_2"
      acceleration_scaling: 0.5
      velocity_scaling: 0.5
      skill_type: "joint_move_to"
      relative_position: [0.0,0.0,0.0]
      relative_orientation: [0.0,0.0,0.0,1.0]

      relative_position_max_variation: [0.02,0.02,0.02]
      acceleration_scaling_max_variation: 0.1
      velocity_scaling_max_variation: 0.1

    insert:
      skill_type: "simple_touch"
      goal_twist_frame: "link6"
      release: 0.06
      release_condition: 0
      relative_target: true

      goal_twist: [0.05, 0, 0, 0, 0, 0]
      target_force: 200.0

      # goal_twist_max_variation: [0.01, 0, 0, 0, 0, 0]
      # target_force_max_variation: 5

    return:
      skill_type: "cartesian_position"
      frame: "open_tip"         # the movement is refered to this frame
      position: [0,0,-0.02]     # traslation to respect the three axes. Position and orientation are alternative to rotZdeg and others.
      quaternion: [0,0,0,1]  # rotation to respect the three axes
      linear_velocity_m_s: 0.05
      angular_velocity_rad_s: 0.7


    move_to_hole:
      target_frame: "hole_2"
      acceleration_scaling: 0.5
      velocity_scaling: 0.5
      skill_type: "joint_move_to"
      relative_position: [0.0,0.0,0.0]
      relative_orientation: [0.0,0.0,0.0,1.0]

    move_to_coke:
      target_frame: "coke_approach"
      acceleration_scaling: 0.5
      velocity_scaling: 0.5
      skill_type: "joint_move_to"
      relative_position: [0.0,0.0,0.0]
      relative_orientation: [0.0,0.0,0.0,1.0]
