tf_params:
  - {name: "visual_coke"  , frame: "coke_can",    position: [0.01,  0.01,  0.00], quaternion: [0.0, 0.0, 0.0, 1.0]}
  - {name: "coke_approach", frame: "visual_coke", position: [0.0,   0.0,   0.20], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "coke_grasp"   , frame: "visual_coke", position: [0.0,   0.0,    0.0], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "home"         , frame: "world",       position: [0.0,   1.3,    1.8], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "hole_1"       , frame: "world",       position: [0.66,  1.010, 1.35], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "hole_2"       , frame: "world",       position: [0.33,  1.010, 1.35], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "hole_3"       , frame: "world",       position: [0.0,   1.010, 1.35], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "hole_4"       , frame: "world",       position: [-0.33, 1.010, 1.35], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "on_hole_1"    , frame: "world",       position: [0.66,  1.010, 1.15], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "on_hole_2"    , frame: "world",       position: [0.33,  1.010, 1.30], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "on_hole_3"    , frame: "world",       position: [0.0,   1.010, 1.15], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "on_hole_4"    , frame: "world",       position: [-0.33, 1.010, 1.15], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "in_hole_1"    , frame: "world",       position: [0.66,  1.010, 1.08], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "in_hole_2"    , frame: "world",       position: [0.33,  1.010, 1.08], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "in_hole_3"    , frame: "world",       position: [0.0,   1.010, 1.08], quaternion: [0.0, 1.0, 0.0, 0.0]}
  - {name: "in_hole_4"    , frame: "world",       position: [-0.33, 1.010, 1.08], quaternion: [0.0, 1.0, 0.0, 0.0]}
